default_platform(:android)

platform :android do
  # Test lane
  desc "Runs all the tests"
  lane :build_test do
    gradle(task: "test")
  end

  # Build debug APK
  desc "Builds the debug APK"
  lane :build_debug do
    gradle(task: "assembleDebug")
  end

  # Build release APK
  desc "Builds the release APK"
  lane :build_release do
    gradle(task: "assembleRelease")
  end

  # set_version
  lane :git_version_code do
    sh("git rev-list --count HEAD").strip
  end

  lane :git_version_name do
    tag = sh("git describe --tags --abbrev=0", log: false).strip rescue nil
    tag || "0.1.0-dev"
  end

  lane :set_version do
    vc = android_get_version_code(gradle_file: "app/build.gradle.kts") || git_version_code
    vn = android_get_version_name(gradle_file: "app/build.gradle.kts") || git_version_name

    UI.message("Version set: #{vn} (#{vc})")
  end

  lane :release_notes_from_git do
    notes = sh("git log -1 --pretty=%B").strip
    notes.empty? ? "No release notes provided." : notes
  end

  # Upload Debug APK to Firebase App Distribution
  desc "Upload Debug APK to Firebase App Distribution"
  lane :upload_debug_firebase do
    notes = release_notes_from_git
    version_code = android_get_version_code(gradle_file: "app/build.gradle.kts") || git_version_code
    version_name = android_get_version_name(gradle_file: "app/build.gradle.kts") || git_version_name
    firebase_app_distribution(
      app: "1:1074263516470:android:e416942e842cbf8fa43f97",
      service_credentials_file: File.expand_path("service_account.json", __dir__),
      testers: "dungnb@nal.vn, dungletk2109@gmail.com",
      release_notes: "[DEBUG BUILD] Version: #{version_name} (#{version_code})\n#{notes}"
    )
  end

  # Upload Release APK to Firebase App Distribution
  desc "Upload Release APK to Firebase App Distribution"
  lane :upload_release_firebase do
    notes = release_notes_from_git
    version_code = android_get_version_code(gradle_file: "app/build.gradle.kts") || git_version_code
    version_name = android_get_version_name(gradle_file: "app/build.gradle.kts") || git_version_name
    firebase_app_distribution(
      app: "1:1074263516470:android:e416942e842cbf8fa43f97",
      service_credentials_file: File.expand_path("service_account.json", __dir__),
      testers: "dungnb@nal.vn, dungletk2109@gmail.com",
      release_notes: "[RELEASE BUILD] Version: #{version_name} (#{version_code})\n#{notes}"
    )
  end

  desc "Build debug APK and upload to Firebase App Distribution"
  lane :debug do
    set_version
    build_test
    build_debug
    upload_debug_firebase
  end

  desc "Build release APK and upload to Firebase App Distribution"
  lane :release do
    set_version
    build_release
    upload_release_firebase
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    build_release
    upload_to_play_store
  end
end
