# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build"
  lane :beta do
    gradle(task: "clean assembleRelease")
    firebase_app_distribution(
        app: "1:1074263516470:android:e416942e842cbf8fa43f97",
        service_credentials_file: "/Users/dungnb/Documents/DungNB/NalProject/BenAssistant/fastlane/ben-ai-assistant-firebase-adminsdk-fbsvc-6bf38f72de.json",
        testers: "dungnb@nal.vn,dungletk2109@gmail.com",
        release_notes: "Beta build từ fastlane"
      )
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
